version: '3.4'

services:

  demands:
    image: ${REGISTRY:-eva}/demands:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Demands/Dockerfile
    healthcheck:
      test: "curl --fail http://localhost/liveness || exit 1"
      interval: 3s
      retries: 10
  
  demands-dapr:
    image: "daprio/daprd:1.6.0"
    network_mode: "service:demands"
    depends_on:
      demands:
        condition: service_healthy
    command: [ "./daprd","-app-id", "demands","-app-port", "80"  ,"-config", "/configuration/eshop-config.yaml" ]


  aggregator:
    image: ${REGISTRY:-eva}/aggregator:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Gateways/Aggregator/Dockerfile
    healthcheck:
      test: "curl --fail http://localhost/liveness || exit 1"
      interval: 3s
      retries: 10

  aggregator-dapr:
    image: "daprio/daprd:1.6.0"
    network_mode: "service:aggregator"
    depends_on:
      aggregator:
        condition: service_healthy
      demands-dapr:
        condition: service_started
      single-sign-on-dapr:
        condition: service_started
    command: [ "./daprd","-app-id", "aggregator","-app-port", "80" ,"-config", "/configuration/eshop-config.yaml" ]


  single-sign-on:
    image: ${REGISTRY:-eva}/single-sign-on:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/SingleSignOn/Dockerfile
    healthcheck:
      test: "curl --fail http://localhost/liveness || exit 1"
      interval: 3s
      retries: 10

  single-sign-on-dapr:
    image: "daprio/daprd:1.6.0"
    network_mode: "service:single-sign-on"
    depends_on:
      single-sign-on:
        condition: service_healthy
    command: [ "./daprd","-app-id", "single-sign-on","-app-port", "80" ,"-config", "/configuration/eshop-config.yaml" ]

    
