version: '3.4'

services:

  maildev:
    image: maildev/maildev
    ports:
      - "5500:80"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"

  redis:
    image: redis:alpine
    ports:
      - "5379:6379"

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"
  
  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - "5411:9411"
  
  agile_config:
    image: kklldog/agile_config:latest
    ports:
      - "5005:5000"
    environment:
      - TZ=Asia/Shanghai
      - adminConsole=true
      - db:provider=mysql
      - db:conn= database=configcenter;data source=${EXTERNAL_DNS_NAME_OR_IP};User Id=root;password=Password@1;port=3306
  
  webstatus:
    image: xabarilcoding/healthchecksui:5.0.0

  dapr-placement:
    image: "daprio/dapr:1.6.0"
    command: [ "./placement", "-port", "50000", "-log-level", "debug" ]
    ports:
      - "50000:50000"
  
  mysql:
    command:
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    image: mysql:latest
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: Password@1
    ports:
      - "3306:3306"
    volumes:
      - /usr/local/docker/mysql/data:/var/lib/mysql
  
