version: '3.4'

services:

  maildev:
    image: maildev/maildev
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "5500:80"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "5672:5672"

  redis:
    image: redis:alpine
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "5379:6379"

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - TZ=Asia/Shanghai
    ports:
      - "5340:80"
  
  zipkin:
    image: openzipkin/zipkin-slim
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "5411:9411"
  
  webstatus:
    image: xabarilcoding/healthchecksui:5.0.0
    environment:
      TZ: Asia/Shanghai
    ports:
      - "5107:80"

  dapr-placement:
    image: "daprio/dapr:latest"
    command: [ "./placement", "-port", "50000", "-log-level", "debug" ]
    environment:
      TZ: Asia/Shanghai
    ports:
      - "50000:50000"
  
  agile_config:
    image: kklldog/agile_config:latest
    ports:
      - "5005:5000"
    environment:
      - TZ=Asia/Shanghai
      - adminConsole=true
      - db:provider=mysql
      - db:conn= database=configcenter;data source=${EXTERNAL_DNS_NAME_OR_IP};User Id=root;password=${EXTERNAL_PASS_WORD};port=3306
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: "curl http://localhost:5005/admin/PasswordInited"
      interval: 1s
      retries: 120
  
  mysql:
    command:
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    image: mysql:latest
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${EXTERNAL_PASS_WORD}
    ports:
      - "3306:3306"
    volumes:
      - ${EXTERNAL_BASE_PATH}docker/mysql/data:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h localhost -u root --password=${EXTERNAL_PASS_WORD}"
      interval: 1s
      retries: 120
      
  
