version: '3.4'

services:

  demands:
    image: ${REGISTRY:-eva}/demands:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Demands/Dockerfile
    healthcheck:
      test: "curl --fail http://localhost/liveness || exit 1"
      interval: 3s
      retries: 10
      
  demands-dapr:
    image: "daprio/daprd:1.7.0"
    network_mode: "service:demands"
    depends_on:
      demands:
        condition: service_healthy
    command: ["./daprd","-app-id", "demands","-app-port", "80"]


  http-aggregator:
    image: ${REGISTRY:-eva}/http-aggregator:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Gateways/ProxyAggregator/Dockerfile
    healthcheck:
      test: "curl --fail http://localhost/liveness || exit 1"
      interval: 3s
      retries: 10

  http-aggregator-dapr:
    image: "daprio/daprd:1.7.0"
    network_mode: "service:http-aggregator"
    depends_on:
      http-aggregator:
        condition: service_healthy
      demands-dapr:
        condition: service_started
    command: [ "./daprd","-app-id", "http-aggregator","-app-port", "80"]

    