version: '3.4'

services:

  demands:
    image: ${REGISTRY:-eva}/demands:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Demands/Dockerfile

  demands-dapr:
    image: "daprio/daprd:1.6.0"
    depends_on:
      - demands
    command: ["./daprd","-app-id", "demands","-app-port", "80"]

  http-aggregator:
    image: ${REGISTRY:-eva}/http-aggregator:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Gateways/HttpAggregator/Dockerfile
    depends_on:
      - demands

  http-aggregator-dapr:
    image: "daprio/daprd:1.6.0"
    network_mode: "service:http-aggregator"
    depends_on:
      - http-aggregator
    command: [ "./daprd","-app-id", "http-aggregator","-app-port", "80"]
    