apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: config
  namespace: eshop
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://10.181.22.62:5411/api/v2/spans"